### ISSUE TITLE
Error getting connection from data source HikariDataSource (HikariPool-0)

### ISSUE THREAD

**Issue by goRaspy** [RWTH-i5-IDSG/steve-plugsurfing#2] opened 2016-07-29 08:48 UTC
I have sometimes problem with database on test server.

When I log to steve-ps I get these error message :+1: 

![image](https://cloud.githubusercontent.com/assets/10080460/17242463/7971dfd0-5577-11e6-851e-ce715b685f1b.png)

I am not really sure of what happen. This is probably due to an very important number of active transaction. It seems only append with the PS version. So I do not know if the problem do not come from PS server which should be down (after a reboot of Steve everything is fixed).

After somes google check, it seems that problem could be cause by a not coherent configuration between database (MariaDB in my case) and HikariCP. I should be interested to test somes change on max_connections and timeout of Hiraki but I can't find the config files.

FYI part of logs : 

[logstevepbhiraki.txt](https://github.com/RWTH-i5-IDSG/steve-plugsurfing/files/390165/logstevepbhiraki.txt)

**Comment by goekay** [comment] 2016-07-29 09:02
there is no database configuration difference between ps and core version. so, i think it is unlikely that it only occurs in ps version. if anything, it should occur in core, as well.

**Comment by goRaspy** [comment] 2016-07-29 09:06
Ok thanks, I not sure that not happen with steve core. I just never get the case.

Do you know how can I make somes test with HikariCP settings ?

**Comment by goekay** [comment] 2016-07-29 09:07
the configuration can be found here: https://github.com/RWTH-i5-IDSG/steve-plugsurfing/blob/master/src/main/java/de/rwth/idsg/steve/config/BeanConfiguration.java#L65-L77

**Comment by goRaspy** [comment] 2016-07-29 09:08
Ok many thanks. I will make somes try.

**Comment by goekay** [comment] 2016-07-29 09:25
i just successfully tested steve-ps with MariaDB 10.1.9, there were no problems. two questions to clarify the situation:
1. is there a pattern when the problem occurs (always for every db activity, under some heavy load, etc.)?
2. what is your mariadb version?

**Comment by goekay** [comment] 2016-07-29 09:48
tested with latest stable release (MariaDB 10.1.16) as well. no problems.

**Comment by schemar** [comment] 2016-07-29 09:52
Logging into the manager works for me on:
- Code: latest `master`
- Java: openjdk version "1.8.0_102"
- DB: mysql  Ver 15.1 Distrib 10.1.16-MariaDB

**Comment by goRaspy** [comment] 2016-07-29 10:29
My mistake I use : 
Your MySQL 5.7.13-0ubuntu0.16.04.2 on this server.

When I look at mysql logs it seems that I have a size problem with the btmp.1 file.

Do you think it is interesting to change for mariadb ?

**Comment by goRaspy** [comment] 2016-07-29 10:30
There is no identificated pattern for the problem :(

**Comment by goRaspy** [comment] 2016-07-29 11:10
I discovered that the server was under attack by brute force since yesterday. I think it should be linked.

I just updated system and enforce security. Will see if the problem come back.

Many thanks

**Comment by goekay** [comment] 2016-07-29 11:13
please close the issue afterwards, if the problem is not related to steve/mysql/mariadb

**Closed as completed** 2016-07-29 11:22 UTC

**Comment by goekay** [comment] 2016-08-04 09:01
correction: the referenced issue was a typo. it should have been #4
